version: '3.4'
services:
  eShopDb:
    container_name: eShop-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Abc@12345
    networks:
        - backend
    ports:
      - 5000:1433
    volumes:
        - sql-sever:/var/opt/mssql

  eshop.backendapi:
    container_name: eShop-api
    image: ${DOCKER_REGISTRY-}eshopbackendapi
    build:
      context: .
      dockerfile: eShop.BackendApi/Dockerfile
    networks:
        - backend
    depends_on:
        - eShopDb

  eshop.adminapp:
    container_name: eShop-adminapp
    image: ${DOCKER_REGISTRY-}eshopadminapp
    build:
      context: .
      dockerfile: eShop.AdminApp/Dockerfile
    depends_on:
      - eshop.backendapi


  eshop.webapp:
    container_name: eShop-webapp
    image: ${DOCKER_REGISTRY-}eshopwebapp
    build:
      context: .
      dockerfile: eShop.WebApp/Dockerfile
    depends_on:
      - eshop.backendapi


volumes:
  sql-sever:
    external: true
     
networks:
  backend:
    external: true